all:
  hosts:

    prod:
      ansible_host: zhdk-leihs-prod-v6.ruby.zhdk.ch
      leihs_external_hostname: leihs.zhdk.ch
      db_backup_on_deploy: Yes
      leihs_send_mails: Yes
      db_backup_keep_days: 4
      db_backup_nigthly_enabled: Yes
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://ausleihe.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_prod_agw_app_id}}'
      agw_app_secret: '{{zhdk_prod_agw_app_secret}}'
      zhdkaad_client_id: 6a35749b-1bfc-4765-95e8-336e49441390

    staging:
      ansible_host: zhdk-leihs-staging.ruby.zhdk.ch
      leihs_external_hostname: staging.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: Yes
      db_backup_nigthly_enabled: No
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://staging.leihs.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_staging_agw_app_id}}'
      agw_app_secret: '{{zhdk_staging_agw_app_secret}}'
      zhdkaad_client_id: b26f2d22-1709-4b12-98b8-6802314f3dc1

    test:
      ansible_host: zhdk-leihs-test.ruby.zhdk.ch
      leihs_external_hostname: test.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: Yes
      db_backup_nigthly_enabled: No
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://test.leihs.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_test_agw_app_id}}'
      agw_app_secret: '{{zhdk_test_agw_app_secret}}'
      zhdkaad_client_id: b6d7c311-51bf-4acc-b676-ad33c41c1612

    demo:
      ansible_host: zhdk-leihs-demo.ruby.zhdk.ch
      leihs_external_hostname: demo.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: No
      db_backup_nigthly_enabled: No
      database_dump_restore_file_path: '{{playbook_dir}}/../database/db/demo.pgbin'

  children:

    leihs_server:
      hosts:
        demo:
        prod:
        test:
        staging:
      vars:
        ansible_user: root
        ssh_keys_present:
          - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
          - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
          - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"
        ssh_keys_absent: []

    zhdk_secrets:
      hosts:
        prod:
        staging:
        test:
