dev:
  hosts:
    jan:
    manuel:
    nimaai:
    tom:
    uvb:
  vars:
    ansible_host: '{{inventory_hostname}}-leihs.ruby.zhdk.ch'
    leihs_external_hostname: '{{inventory_hostname}}.leihs.rubydev.zhdk.ch'

leihs_server:
  hosts:
    demo:
    prod:
    staging:
    test:
  children:
    dev:

restricted:
  hosts:
    test:
    staging:
  children:
    dev:

zhdk:
  hosts:
    prod:
    staging:
    test:
  children:
    dev:

zhdk_secrets:
  hosts:
    prod:
    staging:
    test:
  children:
    dev: