all:
  hosts:

    prod:
      ansible_host: zhdk-leihs-prod-v6.ruby.zhdk.ch
      leihs_external_hostname: leihs.zhdk.ch
      db_backup_on_deploy: Yes
      leihs_send_mails: Yes
      db_backup_keep_days: 4
      db_backup_nigthly_enabled: Yes
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://ausleihe.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_prod_agw_app_id}}'
      agw_app_secret: '{{zhdk_prod_agw_app_secret}}'

    staging:
      ansible_host: zhdk-leihs-staging.ruby.zhdk.ch
      leihs_external_hostname: staging.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: Yes
      db_backup_nigthly_enabled: No
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://staging.leihs.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_staging_agw_app_id}}'
      agw_app_secret: '{{zhdk_staging_agw_app_secret}}'

    test:
      ansible_host: zhdk-leihs-test.ruby.zhdk.ch
      leihs_external_hostname: test.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: Yes
      db_backup_nigthly_enabled: No
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://test.leihs.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_test_agw_app_id}}'
      agw_app_secret: '{{zhdk_test_agw_app_secret}}'

  children:

    leihs_server:
      hosts:
        demo:
        prod:
        test:
        staging:
      vars:
        ansible_user: root
        maintenance_page_body_paragraphs_html: ["⚠️ Leihs deploy on {{leihs_external_hostname}} is running. ⚠️"]
        leihs_virtual_hosts:
        - hostname: '{{leihs_external_hostname}}'
          ip: '*'
          ssl_certificate_file: '/etc/ssl/localcerts/{{ansible_host}}.crt'
          ssl_certificate_key_file: '/etc/ssl/localcerts/{{ansible_host}}.key'
          force_redirect_to_https: yes

    restricted:
      hosts:
        test:
        staging:
      vars:
        restrict_access_via_basic_auth: true
        restrict_access_via_basic_auth_passwords:
          ZHdK-Leihs-Team: "{{zhdk_leihs_team_basic_auth_password}}"


    zhdk:
      hosts:
        staging:
        test:
        # disables basic auth for prod
        # enable after sync is updated accordingly
        # prod:

    zhdk_secrets:
      hosts:
        prod:
        staging:
        test:
