all:
  hosts:

    prod:
      ansible_host: zhdk-leihs-prod-v6.ruby.zhdk.ch
      ansible_user: root
      leihs_external_hostname: leihs.zhdk.ch
      db_backup_on_deploy: Yes
      leihs_send_mails: Yes
      db_backup_keep_days: 4
      db_backup_nigthly_enabled: Yes
      ssh_keys_present:
        - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
        - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
        - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"
      ssh_keys_absent:
        - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
      reverse_proxy_custom_config: |
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://ausleihe.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_prod_agw_app_id}}'
      agw_app_secret: '{{zhdk_prod_agw_app_secret}}'

    staging:
      ansible_host: zhdk-leihs-staging.ruby.zhdk.ch
      ansible_user: root
      leihs_external_hostname: staging.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: Yes
      db_backup_keep_days: 4
      db_backup_nigthly_enabled: No
      ssh_keys_present:
        - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
        - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
        - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"
      ssh_keys_absent:
        - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
      reverse_proxy_custom_config: |
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
      agw_auth_external_base_url: https://staging.leihs.zhdk.ch
      agw_auth_port: 3333
      agw_auth_private_key: '{{auth_system_master_private_key}}'
      agw_auth_public_key: '{{auth_system_master_public_key}}'
      agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
      agw_app_id: '{{zhdk_staging_agw_app_id}}'
      agw_app_secret: '{{zhdk_staging_agw_app_secret}}'

    demo:
      ansible_host: zhdk-leihs-demo.ruby.zhdk.ch
      ansible_user: root
      leihs_external_hostname: demo.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: No
      db_backup_keep_days: 4
      db_backup_nigthly_enabled: No
      database_dump_restore_file_path: '{{playbook_dir}}/../database/db/demo.pgbin'

  children:

    leihs_server:
      hosts:
        demo:
        prod:
        staging:

    zhdk_secrets:
      hosts:
        prod:
        staging:
