leihs_server:
  hosts:
    demo:
    prod:
    staging:
    test:

restricted:
  hosts:
    test:
    staging:

zhdk:
  hosts:
    prod:
    staging:
    test:

zhdk_secrets:
  hosts:
    prod:
    staging:
    test: