prod-leihs-deploy:
  include: cider-ci/context-components/deploy-defaults.yml
  name: Deploy to zhdk-leihs-prod.ruby.zhdk.ch
  depends_on:
    deploy to staging:
      type: job
      job_key: staging-leihs-deploy
      states: [passed]
  run_when:
    "deploy at 18:00 UTC on branch deploy":
      type: cron
      value: "00 18 * * *"
      branch_include_match: ^deploy$
  context:
    task_defaults:
      exclusive_global_resources:
        "zhdk-leihs-prod.ruby.zhdk.ch": true
      environment_variables:
        DEPLOY_TARGET_INVENTORY: "hosts.yml --limit prod"
        STATUS_PAGE_URL: "https://ci.zhdk.ch/cider-ci/ui/workspace/trials/{{CIDER_CI_TRIAL_ID}}"
        LOCAL_CACHE_DIR: "/tmp/leihs-build-cache" # build cache same as for the tests
    tasks:
      deploy:
        scripts:
          deploy:
            body: ./bin/prod-leihs-deploy
